In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [44]:
df=pd.read_csv("glass.csv")

In [57]:
df.shape

(214, 10)

In [45]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [46]:
df.describe()

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516523   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009    2.780374  
std      1.423153    0.497219    0.097439    2.103739  
min      5.430000    0.000000    0.000000    1.000000  
25%      8.240000    0.000000    0.000000    1.000000  
50%      8.600000    0.000000    0.000000    2.000000  
75%      9.172500    0.000000    0.100000    3.000000  
max     16.190000    3.150000    0.510000    7.000000

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [48]:
x = df.drop(["Fe", "Ba", "Type"], axis=1)
y=df["Type"]

In [49]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 10)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(149, 8)
(149,)
(65, 8)
(65,)


In [50]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train_scale=scaler.transform(X_train)
X_test_scale=scaler.transform(X_test)

X_train_scale

array([[-0.89210363,  0.13317649,  0.49574225, ..., -0.31600533,
        -0.3503814 , -0.56564398],
       [ 0.57659186,  0.32024669, -1.61298193, ...,  1.82201814,
        -0.3503814 , -0.56564398],
       [ 2.33122808, -1.86223892,  1.58022897, ..., -0.45394233,
         0.86417923, -0.56564398],
       ...,
       [-0.71014136,  0.59045919, -0.46824594, ..., -0.41945808,
        -0.3503814 , -0.56564398],
       [-0.55417369,  0.6736015 ,  0.19449594, ..., -0.30910848,
        -0.3503814 ,  0.74782542],
       [-0.46319256,  0.63203035, -0.20716581, ..., -0.41256123,
        -0.3503814 ,  0.63836964]])

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
model_KNN=KNeighborsClassifier(n_neighbors=15)
model_KNN.fit(X_train_scale,y_train)
y_pred=model_KNN.predict(X_test_scale)

In [53]:
y_pred

array([2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 7, 2, 2, 2, 1, 1, 2, 2, 2,
       6, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 7, 2, 7, 2, 2, 2, 2, 1, 2,
       2, 1, 2, 1, 2, 2, 1, 7, 1, 1, 7, 7, 5, 1, 1, 2, 7, 2, 2, 1, 7],
      dtype=int64)

In [54]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cfm =confusion_matrix(y_test,y_pred)

print(cfm)

print("Classification report: ")

print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test, y_pred)
print("Accuracy of the model: ",acc)

[[12 13  0  0  0  0]
 [ 3 14  0  0  0  0]
 [ 4  3  0  0  0  0]
 [ 0  3  0  1  0  0]
 [ 0  1  0  0  1  2]
 [ 0  2  0  0  0  6]]
Classification report: 
              precision    recall  f1-score   support

           1       0.63      0.48      0.55        25
           2       0.39      0.82      0.53        17
           3       0.00      0.00      0.00         7
           5       1.00      0.25      0.40         4
           6       1.00      0.25      0.40         4
           7       0.75      0.75      0.75         8

    accuracy                           0.52        65
   macro avg       0.63      0.43      0.44        65
weighted avg       0.56      0.52      0.49        65

Accuracy of the model:  0.5230769230769231


In [55]:
y

0      1
1      1
2      1
3      1
4      1
      ..
209    7
210    7
211    7
212    7
213    7
Name: Type, Length: 214, dtype: int64

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred_train=model_KNN.predict(X_train_scale)
cfm =confusion_matrix(y_train,y_pred_train)

print(cfm)

print("Classification report: ")

print(classification_report(y_train,y_pred_train))

acc=accuracy_score(y_train, y_pred_train)
print("Accuracy of the model: ",acc)

[[39  6  0  0  0  0]
 [ 8 49  0  1  1  0]
 [ 3  7  0  0  0  0]
 [ 3  2  0  3  0  1]
 [ 3  0  0  0  1  1]
 [ 2  1  0  0  0 18]]
Classification report: 
              precision    recall  f1-score   support

           1       0.67      0.87      0.76        45
           2       0.75      0.83      0.79        59
           3       0.00      0.00      0.00        10
           5       0.75      0.33      0.46         9
           6       0.50      0.20      0.29         5
           7       0.90      0.86      0.88        21

    accuracy                           0.74       149
   macro avg       0.60      0.51      0.53       149
weighted avg       0.69      0.74      0.70       149

Accuracy of the model:  0.738255033557047
